# Etapa de construcción
FROM node:20-alpine AS builder

WORKDIR /app

# Copiar código fuente
COPY ./admin-veterinaria/ ./

# Activar pnpm y compilar
RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install
RUN pnpm build

# Etapa de producción
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx-frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]